language: rust
rust: stable
os: linux
dist: trusty

jobs:
  - name: "Tooling tests"
    before_script:
      - rustup component add clippy
    script:
      - cargo clippy
      - cargo build --verbose
      - cargo test --verbose
  - name: "Language tests"
    before_script:
      - nvm install 11.1.0
    script:
      - node test test_cases/
  - name: "Python tests"
    before_script:
      - nvm install 11.1.0
      - pyenv install -v 3.9-dev
      - pyenv global 3.9-dev
    script:
      - node test test_cases/python/ "--features inline-python --release"
      - python3 inline/src.py

cache: cargo
