language: rust
rust: stable
os: linux
dist: trusty

jobs:
  - name: "Tooling tests"
    before_script:
      - rustup component add clippy
    script:
      - cargo clippy
      - cargo build --verbose
      - cargo test --verbose
  - name: "Language tests"
    before_script:
      - nvm install 11.1.0
    script:
      - node test test_cases/
  - name: "Python tests"
    language: python
    # Later versions won't work, god knows why
    python: 3.6
    before_script:
      - nvm install 11.1.0
      - curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -o rustup.sh
      - echo 1 | sh rustup.sh -y
      - . $HOME/.cargo/env
      - rustup install stable
    script:
      - node test test_cases/python/ "--features inline-python --release"
      - python3 inline/src.py

cache: cargo
