language: rust
rust: stable

before_script:
  - rustup component add clippy
  - nvm install 11.1.0
script:
  - cargo clippy
  - cargo build --verbose
  - cargo test --verbose
  - node test

cache: cargo