language: rust
rust: stable

matrix:
  include:
    - name: "Interior tests"
      language: rust
      rust: stable
      script:
        - cargo build --verbose
        - cargo test --verbose
    - name: "Exterior tests"
      language: rust
      rust: stable
      before_script:
        - nvm install 11.1.0
      script:
        - node test

cache: cargo