language: rust
rust: stable
os: linux
dist: trusty

jobs:
  - name: "Tooling tests"
    before_script:
      - rustup component add clippy
    script:
      - cargo clippy
      - cargo build --verbose
      - cargo test --verbose
  - name: "Language tests"
    before_script:
      - nvm install 11.1.0
    script:
      - node test test_cases/
  - name: "Python tests"
    env:
      - PYENV_VERSION=3.9.1
    before_script:
      - nvm install 11.1.0
      - cd $(pyenv root) && git checkout master && git pull && cd -
      - sudo apt-get install -y build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python-openssl git
      - pyenv install --list
      - LDFLAGS="-L/usr/lib/openssl-1.0" CFLAGS="-I/usr/include/openssl-1.0" pyenv install $PYENV_VERSION
      - pyenv versions
      - pyenv global $PYENV_VERSION
    script:
      - python -v
      - node test test_cases/python/ "--features inline-python --release"
      - python3 inline/src.py

cache: cargo
