language: rust
rust: stable

matrix:
  include:
    - name: "Interior tests"
      language: rust
      rust: stable
      script:
        - cargo build --verbose
        - cargo test --verbose
    - name: "Exterior tests"
      language: node.js
      node_js: "12.0"
      script:
        - node test

cache: cargo