[package]
name = "arsm"
version = "0.1.0"
authors = ["Joshua B. <zippymagician1@gmail.com>"]
edition = "2018"

[[bin]]
bench = false
path = "src/main.rs"
name = "arsm"

[dependencies]
lazy_static = "1.4.0"
clap = "2.33.3"