[package]
name = "arsm"
version = "0.2.0"
authors = ["Joshua B. <zippymagician1@gmail.com>"]
edition = "2018"

[[bin]]
bench = false
path = "src/main.rs"
name = "arsm"

[dependencies]
clap = "2.33.3"
lazy_static = "1.4.0"
num-traits = "0.2"